on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
  steps:
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5.1

    - name: Current branch name
      run: |
        echo "${{ steps.branch-name.outputs.current_branch }}"
      # Outputs: "feature/test" current PR branch.

    - name: Running on a non tag based branch and a PR branch.
      if: steps.branch-name.outputs.is_default == 'false'
      run: |
        echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
      # Outputs: "Running on branch: feature/test".

    - name: Running on a pull request (i.e non tag based branch).
      if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'false'
      run: |
        echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
      # Outputs: "Running on branch: feature/test".

    - name: Get Ref brach name
      run: |
        echo "${{ steps.branch-name.outputs.ref_branch }}"
      #  Outputs: "1/merge"

    - name: Get Head Ref branch name (i.e The current pull request branch)
      run: |
        echo "${{ steps.branch-name.outputs.head_ref_branch }}"
      # Outputs: "feature/test" current PR branch.

    - name: Get Base Ref branch name (i.e The target of a pull request.)
      run: |
        echo "${{ steps.branch-name.outputs.base_ref_branch }}"
      # Outputs: "main".
